name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos
      COMMIT: ${{ github.sha }}
      REPO: shipping
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/shipping/shipping/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - uses: actions/checkout@v2

      - run: touch starting_test_SetupJDK18_25
      - run: rm starting_test_SetupJDK18_25
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: touch starting_test_CacheMavenpackages_30
      - run: rm starting_test_CacheMavenpackages_30
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - run: touch starting_test_BuildwithMaven_37
      - run: rm starting_test_BuildwithMaven_37
      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml

      - run: touch starting_test_UnitTests_40
      - run: rm starting_test_UnitTests_40
      - name: Unit Tests
        run: mvn -q test

      - run: touch starting_test_IntegrationTests_43
      - run: rm starting_test_IntegrationTests_43
      - name: Integration Tests
        run: mvn integration-test

      # Upload coverage results to coveralls
      - run: touch starting_test_SubmitCoveralls_47
      - run: rm starting_test_SubmitCoveralls_47
      - name: Submit Coveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: mvn -DrepoToken=${COVERALLS_TOKEN} -DserviceJobId=${GITHUB_RUN_ID} -Dbranch=${GITHUB_REF} -DpullRequest=${GITHUB_HEAD_REF} -DserviceName=GITHUB verify jacoco:report coveralls:report

      # Push to dockerhub
      - run: touch starting_test_PushtoDockerHub_53
      - run: rm starting_test_PushtoDockerHub_53
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          dockerfile: docker/shipping/Dockerfile
          path: target/
          repository: ${{ env.GROUP }}/${{ env.REPO }}
          tag_with_ref: true
          tag_with_sha: true
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'UT-SE-Research'
          destination-repository-name: 'ci-analyzes'
          target-branch: '1676488234-be4bc7c'
          target-directory: 'shipping/.github/workflows/main/test'
